// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl = process.env["DATABASE_URL"];
const shadowDatabaseUrl = process.env["SHADOW_DATABASE_URL"];

export default defineConfig({
	schema: "prisma/schema.prisma",
	migrations: {
		path: "prisma/migrations",
	},
	datasource: {
		url: databaseUrl,
		shadowDatabaseUrl:
			shadowDatabaseUrl && shadowDatabaseUrl !== databaseUrl
				? shadowDatabaseUrl
				: undefined,
	},
});
